"""sync_latest_schema_and_summaries

Revision ID: fdbe918b9d84
Revises: 26593e71f9a8
Create Date: 2026-09-22 11:36:50.067911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdbe918b9d84'
down_revision: Union[str, Sequence[str], None] = '26593e71f9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'default_tenant'::character varying"))
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.alter_column('conversations', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'default_tenant'::character varying"))
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.alter_column('knowledge_chunks', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'default_tenant'::character varying"))
    op.create_index(op.f('ix_knowledge_chunks_tenant_id'), 'knowledge_chunks', ['tenant_id'], unique=False)
    op.alter_column('knowledge_documents', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'default_tenant'::character varying"))
    op.alter_column('knowledge_documents', 'regulator',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'RBI'::character varying"))
    op.alter_column('knowledge_documents', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('ix_knowledge_documents_effective_from'), 'knowledge_documents', ['effective_from'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_effective_until'), 'knowledge_documents', ['effective_until'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_regulator'), 'knowledge_documents', ['regulator'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_status'), 'knowledge_documents', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_tenant_id'), 'knowledge_documents', ['tenant_id'], unique=False)
    op.alter_column('messages', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'default_tenant'::character varying"))
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'default_tenant'::character varying"))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.alter_column('users', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'default_tenant'::character varying"))
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.alter_column('messages', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'default_tenant'::character varying"))
    op.drop_index(op.f('ix_knowledge_documents_tenant_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_status'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_regulator'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_effective_until'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_effective_from'), table_name='knowledge_documents')
    op.alter_column('knowledge_documents', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('knowledge_documents', 'regulator',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'RBI'::character varying"))
    op.alter_column('knowledge_documents', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'default_tenant'::character varying"))
    op.drop_index(op.f('ix_knowledge_chunks_tenant_id'), table_name='knowledge_chunks')
    op.alter_column('knowledge_chunks', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'default_tenant'::character varying"))
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.alter_column('conversations', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'default_tenant'::character varying"))
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'default_tenant'::character varying"))
    # ### end Alembic commands ###
