"""Create users table

Revision ID: 001
Revises: None
Create Date: 2026-09-18

This migration creates the `users` table for Phase 2 authentication.
It is the first migration in the project history.

Reversible: Yes — downgrade() drops the table and enum type cleanly.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create users table and userrole enum type."""
    userrole_enum = postgresql.ENUM("USER", "ADMIN", name="userrole")
    userrole_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=True),
            primary_key=True,
            nullable=False,
            comment="UUID primary key, generated by the application.",
        ),
        sa.Column(
            "name",
            sa.String(255),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(255),
            nullable=False,
            comment="Stored lowercase-normalized; enforce uniqueness at DB level.",
        ),
        sa.Column(
            "password_hash",
            sa.String(1024),
            nullable=False,
            comment="Argon2id digest. Never stored or returned as plaintext.",
        ),
        sa.Column(
            "role",
            postgresql.ENUM("USER", "ADMIN", name="userrole", create_type=False),
            nullable=False,
            server_default="USER",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
            comment="Soft-disable account without deletion.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    # Unique constraint on email
    op.create_unique_constraint("uq_users_email", "users", ["email"])

    # Index on email for fast lookups during login
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    # Index on id (explicit, though it's already the PK)
    op.create_index("ix_users_id", "users", ["id"], unique=False)


def downgrade() -> None:
    """Drop users table and userrole enum type."""
    op.drop_index("ix_users_id", table_name="users")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_constraint("uq_users_email", "users", type_="unique")
    op.drop_table("users")

    # Drop the PostgreSQL enum type after the table is gone
    userrole_enum = sa.Enum("USER", "ADMIN", name="userrole")
    userrole_enum.drop(op.get_bind(), checkfirst=True)
